# require_relative 'config/environment.rb'
#
# namespace :db do
#
#   desc "Migrate the db"
#   task :migrate do
#     connection_details = YAML::load(File.open('config/database.yml'))
#     ActiveRecord::Base.establish_connection(connection_details)
#     ActiveRecord::Migrator.migrate("db/migrate/")
#   end
#
#   desc "drop and recreate the db"
#   task :reset => [:drop, :migrate]
#
#   desc "drop the db"
#   task :drop do
#     connection_details = YAML::load(File.open('config/database.yml'))
#     File.delete(connection_details.fetch('database')) if File.exist?(connection_details.fetch('database'))
#   end
# end
##############################
##############################
##############################
##############################
##############################
##############################

require_relative 'config/environment.rb'

include ActiveRecord::Tasks
DatabaseTasks.db_dir = 'db'
DatabaseTasks.migrations_paths = 'db/migrate'
seed_loader = Class.new do
  def load_seed
    load "#{ActiveRecord::Tasks::DatabaseTasks.db_dir}/seeds.rb"
  end
end
DatabaseTasks.seed_loader = seed_loader.new
load 'active_record/railties/databases.rake'
